### ISSUE TITLE
deterministic use of text columns to provide OWL/RDF functionality

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#110]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on March 19, 2009 11:37:04_

What capability do you want added or improved? 
The ability to specify already-defined OWL/RDF concepts for the text that appears in a given 
column 

Where do you want this capability to be accessible? 
In Voc2RDF 

What sort of input/command mechanism do you want? 
Use of a prefix in the column header label (e.g., owl:sameAs, owl:inverseOf, rdf:type, 
rdfs:subClassOf, skos:related, skos:broader, skosxl:prefLabel). 

What is the desired output (content, format, location)? 
The qualified label is used to construct the appropriate additional metadata or relationship about 
this term. 

Other details of your desired capability? 
In an ideal world we could generalize the prefixes that are supported. Alternatively, we could 
accept an actual complete URI, thereby allowing any relationship URI. (Ooh, like that idea.)

I am not 100&#37; sure all the labels would be used as predicates. (Annotations, in particular, may 
take some special processing.)

It can be assumed all of these relationships must be used consciously, not blindly. 

What version of the product are you using? 
Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.) 
Note there is a new version of skos out.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=110_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 29, 2009 22:08:28_

I'm adding the "ontmd" label because this is related with some of the prompted
information in ontmd. In general, ontmd should not always ask the user: "Is this is a
map ontology?" the tool should first try to determine whether the submitted ontology
contains certain statements that makes it a mapping (eg. that it contains owl:sameAs
statements). If pre-determined mapping relationships are not found in the ontology,
then then ask the user (?)

**Owner:** carueda  
  **Labels:** -vo ontmd

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [ber...@gmail.com](https://code.google.com/u/105051227815968870037/) on April 13, 2010 12:17:20_

Voc2RDF should concentrate first on providing functionality to create SKOS vocabularies. Will be very hard to 
support OWL etc. ICAN, GEOSS, OGC, Geonetwork.. are all moving towards SKOS.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 30, 2010 14:52:10_

I'll be looking into providing support for SKOS-based vocabularies, mainly according to: issue `#149` , issue `#134` , issue `#133` , which I will "promote" to Beta1 as appropriate.  I'm removing the Beta1 label and lowering to medium priority of this issue #110 .

**Status:** Accepted  
  **Labels:** -Priority-High -Milestone-Beta1 Priority-Medium

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 10:20:13_

See also issue #285 .

**Comment by carueda** [comment]
Implemented in v3.
