### ISSUE TITLE
Should DC values be updated if OMV ones change?

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#111]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 19, 2009 17:40:49_

Not sure this is a bug, but here is the situation: 

What steps will reproduce the problem? 
1. Start creation of new version of an existing ontology
2. Change any of the fields that have both OMV properties with equivalent
DC properties
3. Click "review and upload" to perform review 

What is the expected output? 
The changes are reflected in both the OMV properties and the corresponding
DC ones (?) 

What do you see instead? 
OMV properties properly updated but not the DC ones. See an example below.

NOTE: Should OntMd actually force the equivalent properties to have the
same values? The user may have changed the DC properties by some external
means and then wants to submit the new version. 

\----
Example:

Original ontology contains:

        <omv:hasCreator>C1</omv:hasCreator>
        <dc:creator>C1</dc:creator>

        <omv:description>D1</omv:description>
        <dc:description>D1</dc:description>

After changing the "Creator" and "Brief description" fields (to C2 and D2)
and reviewing:

        <omv:hasCreator>C2</omv:hasCreator>
        <dc:creator>C1</dc:creator>

        <omv:description>D2</omv:description>
        <dc:description>D1</dc:description>

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=111_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 25, 2009 16:57:34_

Haven't received any comments about this. But I think we can postpone this until we
get several other more critical aspects resolved. So, I'm lowering the priority to
medium for now.

**Status:** NeedMoreInfo  
  **Cc:** -grayb...@mbari.org  
  **Labels:** -Priority-High Priority-Medium

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:02:05_

I think ORR should encourage these to be the same values, but not enforce it.

So upon receiving an ontology where there is a conflict, ORR should issue a notification that lists each differing value pair, and let the user leave them unchanged, copy omv->dc, or copy dc->omv. (Same for all button is a nice touch here.)

If a user modifies a property using the metadata field, ORR should prompt with "This will make your ontology metadata ("{value}") different than the document's Dublin Core metadata ("{value}"). Proceed? [Yes, leave different | Yes, overwrite DC value | No, cancel this change]"

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:02:53_

P.S.  If the DC values were originally created by ORR, it would be reasonable to overwrite them silently.

**Comment by carueda** [comment]
This is not an issue in v3 because metadata handling is done in a more consistent way.
