### ISSUE TITLE
Support multiple classes in voc2rdf

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#114]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on March 20, 2009 13:35:15_

What capability do you want added or improved? Voc2RDF should have a convention that allows multiple classes (with instances or subclasses in 
each) to be in one file. Where do you want this capability to be accessible? In voc2RDF text entry. What sort of input/command mechanism do you want? Suggest that if a term appears on a line by itself, it should be treated as a class. Items under 
that term are below that class.

Alternatively, we could specify a column of a particular name, like mmi:class, that would result in 
the term becoming a class if the corresponding entry was 'class'. What is the desired output (content, format, location)? Corresponding OWL. Other details of your desired capability? See also `#113` for info on classes vs instances for all the leaf terms. What version of the product are you using? Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=114_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 20, 2009 13:57:26_

What about having multiple class sections --for example with tabs--, each dedicated
to a particular class? Initially, only one section will be displayed (pretty much as
it is now); but a new  button "Add another class," will create the new section (tab).
 The main point here is simplifying the interface. Having multiple classes and their
instances in the same "Term" textarea (or table), will be very confusing for most
users (if not also for us!).

**Comment by mmisw** [comment]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on March 20, 2009 14:07:40_

That's a pretty good idea. Although it doesn't let me create the text file off-line, then paste all that into one 
window.  But I could live with it.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 29, 2009 21:56:48_

See update in issue `#99` -- MMI Voc2RDF 1.2.0.beta1 (20090329213042)

In preparation for multiple classes, the section for the class and its terms are now
in a tab. Multiple classes could be enabled by including an "Add class" button that
inserts a new tab. 

The proposed central resouceType for the ontology may make more sense when dealing
with multiple classes, but this is still unclear. Would each class be a subclass of
the resourceType? We mentioned this recently, but I realize the current resourceType
vocabulary is defined in terms of individuals, not classes.

**Status:** Accepted  
  **Owner:** carueda

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 10:44:29_

See also issue #110 and issue #285 , and the issue I'm about to create to "Nicely display multiple classes"

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:23:30_

See also issue #324 for nicely displaying multiple classes.

**Comment by carueda** [comment]
Explicitly supported by v3.
