### ISSUE TITLE
Allow multi-line fields in voc2rdf

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#117]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 06, 2009 11:57:37_

(thanks John for this feedback)

I suspect multi-line fields (that is, fields with carriage returns in them)
will not be possible to insert.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=117_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:08:08_

**Cc:** -grayb...@mbari.org

**Comment by carueda** [comment]
Possible in v3.
