### ISSUE TITLE
quoted fields not properly handled

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#121]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 06, 2009 12:24:06_

Thanks John for this feedback:

"The importer took lines with quotes at beginning and end (to escape
embedded commas in CSV) and turned them into double-quotes, then the next
time that was imported it was rejected."

Agree: quotes are not fully supported. I will improve this support as time
permits.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=121_

**Comment by carueda** [comment]
Closely related: #269

**Comment by carueda** [comment]
Fixed in v3.
