### ISSUE TITLE
Immediately enter edit mode when I type in a cell

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#126]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on May 05, 2009 17:11:48_

What capability do you want added or improved? Immediately enter edit mode when I type in a cell Where do you want this capability to be accessible? term table in voc2rdf What sort of input/command mechanism do you want? A regular keystroke Other details of your desired capability? the cell should become editable with a regular keystroke (not having to
type Enter) What version of the product are you using? MMI Voc2RDF 1.2.0.beta3 (20090416204347)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=126_

**Comment by carueda** [comment]
Implemented in v3.
