### ISSUE TITLE
Create row automatically

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#127]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on May 05, 2009 17:14:05_

What capability do you want added or improved? A new row should be immediately available after entering contents for the
last row in the table Where do you want this capability to be accessible? term table in voc2rdf

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=127_

**Comment by carueda** [comment]
General editing much improved in v3.

(the row is not automatically added but there's an explicit button for that, which (besides of course being clicked) can be focused by navigating to it via Tab key.)
