### ISSUE TITLE
metadata panel: improve display including clickable URL when possible

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#146]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 09, 2009 15:39:16_

What steps will reproduce the problem? 1. view any registerd ontology, eg., http://mmisw.org/portal/#http://mmisw.org/ont/mmi/device 2. look at the metadata panel contents What is the expected output? Easy to read field values and clickable links for URLs and MMI-resolvable
URIs if possible What do you see instead? read-only text boxes

Using version MMI Portal 1.5.0.alpha (20090608172543)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=146_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 11, 2009 18:42:11_

**Labels:** -onm ont

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 25, 2009 23:26:34_

Issue 112 has been merged into this issue.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 25, 2009 23:30:39_

Some improvements, now with HTML areas in read-only mode (instead of textboxes). No
clickable links yet.

MMI Portal 1.6.2.alpha7 (20091125232510)

**Status:** Started  
  **Labels:** Usability

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 30, 2009 16:23:06_

Now, a metadata attribute whose whole value looks like a valid URLs is made clickable.

MMI Portal 1.7.0.alpha (20091130161756)

Still pending: detect and make clickable URLs in any part of a value.

**Comment by carueda** [comment]
General handling much improved in v3.
