### ISSUE TITLE
Re-hosting: handle possible version fragment in URI 

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#182]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 15, 2009 11:58:55_

MMI Portal 1.5.0.alpha21 (20090911194652)

In the current implementation of the re-hosting capability, the external
URI is completely opaque for the purposes of versioning. In concrete,
possible version component in that URI is completely ignored. 

Do we want to provide some sort of support in this case?  If so, how would
the mechanism be?

(A preliminary idea: prompt the submitter for some kind of pattern of the
URI that the ORR would use to extract the external version component; also
some rule for sorting the versions chronologically should probably be
indicated. NOTE: I haven't elaborated this idea any further so I don't have
a good estimation of required work for its implementation.)

Please add details (and adjust priority, if that's the case) to this
request in order to decide what to do or not do next.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=182_

**Comment by carueda** [comment]
Closing as "won't fix" -- the suggested functionality (capture and handle a given version pattern in the  ontology URI) seems too complicated for not apparent real benefit.

**Comment by graybeal** [comment]
Well, there's a real benefit, but it may not be one that any users see the need for any time soon. We can always open a new task for this when we have a concrete request.
