### ISSUE TITLE
URLs in sparql HTML formatted response are incorrect

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#185]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 17, 2009 12:05:58_

What steps will reproduce the problem? 
1. do a SPARQL query returning some terms
2. click any of the URLs 

What is the expected output? 
a proper dispatch of the term in the portal, see issue #184

What do you see instead? 
the basic dispatch given by the Ont service, OR NotFound (404) depending on
the case Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=185_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 21, 2010 14:29:20_

**Status:** NeedMoreInfo

**Comment by carueda** [comment]
Cannot reproduce; likely this was fixed long ago.
