### ISSUE TITLE
default version to just YYYYMMDD if possible

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#19]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 01, 2008 20:58:36_

j: default the timestamp component to just YYYYMMDD? otherwise too long
(add the other when YYYYMMDD isn't sufficient) version can be the longer
name if you want

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=19_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 13:26:10_

**Labels:** -Priority-Medium Priority-Low

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 29, 2008 16:58:42_

**Labels:** -org.mmisw.ontmd ontmd

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 21, 2010 14:16:20_

**Labels:** -Type-Defect Type-Enhancement

**Comment by carueda** [comment]
Closing as won't fix and Addressed_in_ORR3.

The general version tagging needs some careful analysis.  (for example, we should "respect" any original versioning --like in the set of SWEET **2.3** ontologies).  What we currently call "version" is basically just a submission timestamp...  Users should have the option to explicitly indicate the version string, etc.
