### ISSUE TITLE
Upload button pop up description should be enhanced

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#197]
_From [cmt1...@gmail.com](https://code.google.com/u/111118716825497141417/) on October 22, 2009 10:14:04_

What capability do you want added or improved? 
Add a more thorough description of the upload button to include all the eligible file types for uploading to the ORR 

Where do you want this capability to be accessible? 
pop up description of the upload button 

What sort of input/command mechanism do you want? 

What is the desired output (content, format, location)? 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=197_

**Comment by carueda** [comment]
Closing as fixed as this has been provided for a long time, in particular regarding the various file types supported for the upload function:

![image](https://cloud.githubusercontent.com/assets/556505/11454966/51606eaa-95f9-11e5-9e30-cf1d90aa0593.png)

(only the OWL/XML was recently added).
