### ISSUE TITLE
Add conditions field for usage metadata

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#198]
_From [cmt1...@gmail.com](https://code.google.com/u/111118716825497141417/) on October 22, 2009 10:17:19_

What capability do you want added or improved? 
Add a field where ontology providers specify the "conditions" under which
author credit is required. 

Where do you want this capability to be accessible? 
Usage/permissions/license metadata tab 

What sort of input/command mechanism do you want? 

What is the desired output (content, format, location)? 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=198_

**Comment by graybeal** [comment]
I'm not sure how strong this need is, or whether a design already exists. But here's more info.

What I envisioned was something like the current CC models, where they are very specific about what re-uses are OK. (If the license is a CC license, this probably isn't needed, the license itself will say whether citation is required.)

So the field would be something like Citation_Criteria and would include any of a number of meaningful keywords (probably need a controlled vocabulary) like: 
* ResearchUse -- if used in other research activities
* CommercialUse -- if used to support commercial development or enterprises
* NonProfitUse -- if used to support non-profit organizations
* EducationalUse -- if used to support educational institutions/activities
* SharedUse -- if used to support a personal activity that is shared with others
* PrivateUse -- if used to support private activity, even if never released
* AnyUse -- includes any the uses described above

The citation technique is another matter, but presumably it includes acknowledging the re-use in an appropriate context (e.g., in the commercial software or products were used).

**Comment by graybeal** [comment]
Let me know what other specific questions you have of me.

**Comment by carueda** [comment]
Closing as won't fix.
If the need persists, please submit issue in new system.
