### ISSUE TITLE
page with summary/next steps after registration

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#201]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 22, 2009 15:02:08_

What capability do you want added or improved? Provide some sort of summary of capabilities upon the registration of a new
ontology. Possible elements include:
- show the link(s) that allow to directly access the ontology
- show some links that allow to access particular terms in the ontology
- show example(s) of queries involving terms/predicates of the registered
  ontology Where do you want this capability to be accessible? Right after a successful registration is completed

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=201_

**Comment by carueda** [comment]
General dispatch upon completion of registration is much improved already in ORR3. In particular, the ontology is immediately displayed. Some aspects here are also captured in other issue entries in the new system. So, closing this one.
