### ISSUE TITLE
select main theme from a number of vocabularies

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#21]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 01, 2008 21:04:44_

j: Eventually we'll want the main theme to be a selection from a number of
vocabularies. Not sure if we'll want every term in each vocabulary though,
or if we'll want the name to match the vocabulary's term. Probably "all of
the above", knowing how these things work. For now, we just need to
populate this from an easily edited table that has 'menu selection', 'term
name', 'uri', and 'description'. The third and fourth make up the tool tip
for each selection. The URI goes into the URI field, and the menu selection
and description go into the drop down). Or something along those lines.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=21_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 29, 2008 16:59:01_

**Labels:** -org.mmisw.ontmd ontmd

**Comment by mmisw** [comment]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on March 13, 2009 12:12:49_

I think all that has to happen here is:

1) The creation of the base vocabularies that can be used (by default) for themes.  This means putting existing 
or new vocabularies into the repository, or getting them from elsewhere.  

2) The incorporation of the labels from those base vocabularies within your drop-down user interface, and 
the inclusion of the corresponding URIs in the field when a label is selected.

3) People can specify other labels and other URIs as desired, or can propose the addition of other 
vocabularies.

(See post below from semweb list for possibly relevant details, I'm thinking of `#2` if we need to solve this 
problem.)

Right now let's use every term from a few vocabularies.  Fast and easy.

Ideas from March 13 post to SemWeb mail list:

(A) Make a list of URIs of terms that I want to re-use -- say, put it in my own ontology of "Terms_To_Use" -- 
then define any new terms that I need, as part of that same list/ontology.  This is very direct reuse.  If 
someone wants to perform reasoning using these terms, they go to the ontology(ies) containing the term to 
do so.  (Not sure though if I want to make them _instances_ of my "Terms_To_Use" class; I'll go back to 
ontology school, Aldo's patterns references and wiki, and the NeON materials/tools, to learn that.)

(B) Create an ontology of new concepts, which in many cases are essentially 'front ends' for the terms I want to 
use (allowing, for example, normalizing the presentation of the labels, or providing extended information), 
and then relate them to the original URIs using an appropriate SKOS relationship or one of my own. This is 
what Pat describes under case (3).

**Labels:** -Priority-Medium Priority-High

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on May 30, 2011 11:50:46_

(re-tagged as enhancement upon general revision of current issues)

**Labels:** -Type-Defect Type-Enhancement

**Comment by carueda** [comment]
John: Assigning to you in case you can add a comment summarizing the idea here as I'm having trouble to remember and follow the previous comments, and also because it's marked as high-priority.

**Comment by graybeal** [comment]
OK, this experience was a little frightening, but thanks to Spotlight I think it's under control.

First, what's called 'main theme' in this thread is now Resource Type in the ontology metadata, IIRC.

The idea was to allow resource types to be chosen from more vocabularies than just the one we created. 

It looks like our workaround -- which follows a short-term approach in these comments -- was to incorporate concepts from multiple vocabularies (by repeating them) into our new ontology. Not the cleanest semantic solution, but it's livable.

So you implemented this conclusion already: "Right now let's use every term from a few vocabularies. Fast and easy." I think this is adequate for now. 

If we run into a semantic stickler, we might have to change our semantic approach (so that a specific term actually maps to a URI from the original vocabulary for that term, whereas now I think we just give it a URI from our vocabulary).

I'd say mark it fixed, or wontfix, as you prefer. Priority definitely not high (given what's already implemented, changed accordingly. 

Also I'll add the original long thread as a comment -- not having that context it was almost impossible to figure out some references here.

**Comment by graybeal** [comment]
From: John Graybeal <graybeal@mbari.org>
Subject: Re: process to discover and adopt/adapt relationships
Date: March 13, 2009 at 11:15:16 AM PDT
To: Pat Hayes <phayes@ihmc.us>
Cc: Semantic Web <semantic-web@w3.org>

Oh, this is excellent.  Thanks to all who have responded to date. To sum up:

I was a little surprised that no other search engines, or search methods, were described.

Pat identified my misunderstanding about imports and usage when he says: one does not have to import an ontology to use its contained concepts.  Case (1) -- the ontology has more concepts than I needed -- was the main issue, and so I think I have 2 reasonably palatable choices to satisfy my use case.

(A) Make a list of URIs of terms that I want to re-use -- say, put it in my own ontology of "Terms_To_Use" -- then define any new terms that I need, as part of that same list/ontology.  This is very direct reuse.  If someone wants to perform reasoning using these terms, they go to the ontology(ies) containing the term to do so.  (Not sure though if I want to make them _instances_ of my "Terms_To_Use" class; I'll go back to ontology school, Aldo's patterns references and wiki, and the NeON materials/tools, to learn that.)

(B) Create an ontology of new concepts, which in many cases are essentially 'front ends' for the terms I want to use (allowing, for example, normalizing the presentation of the labels, or providing extended information), and then relate them to the original URIs using an appropriate SKOS relationship or one of my own. This is what Pat describes under case (3).

Fortunately, I have more practice and instinct for creating definitions than I do for creating ontologies. So once I master the technology I can at least fill it with *something*.

John
