### ISSUE TITLE
Some stats for registered ontologies

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#210]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 08, 2009 20:16:05_

from Luis' 11/5/09 email:

highlight the ontologies that have been downloaded more, and perhaps add a
number right to it.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=210_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 30, 2010 00:38:07_

See issue `#158` for the notification of pageviews to google analytics, which has been already implemented.

In this case, the strategy is to use the google analytics API to get the required data and update the indicators associated with the most popular ontologies. Should be a cronjob-like task.

**Status:** Diagnosed  
  **Labels:** -Priority-Medium Priority-High ont metrics

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/90
