### ISSUE TITLE
Create issue tracker for ontologies

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#230]
_From [ber...@gmail.com](https://code.google.com/u/105051227815968870037/) on December 11, 2009 09:08:14_

Allow an ontology to have an issue list
Ontology can have one..many issues
Issue has status
Issue has one to many comments

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=230_

**Comment by mmisw** [comment]
_From [ber...@gmail.com](https://code.google.com/u/105051227815968870037/) on December 14, 2009 11:25:24_

Summary for interface: 
Simple Web interface for opening and editing issues
Summaries of open issues
Associate issues with working groups
Unique URI for every issue
Summary of issues with all comments  and status

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 22, 2009 00:06:43_

priority critical per OOI semantic prototype requirement.

**Owner:** carueda  
  **Labels:** -Type-Defect Type-Enhancement ooici Usability

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 22, 2009 00:07:08_

**Labels:** -Priority-Medium Priority-Critical

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [jgrayb...@ucsd.edu](https://code.google.com/u/104503330167604998880/) on April 05, 2010 16:53:47_

Not for Beta1, we'll have to look at this after Beta1 release.

**Labels:** -Milestone-Beta1

**Comment by mmisw** [comment]
_From [jgrayb...@ucsd.edu](https://code.google.com/u/104503330167604998880/) on April 05, 2010 16:54:19_

**Labels:** -Priority-Critical Priority-High

**Comment by mmisw** [comment]
_From [jgrayb...@ucsd.edu](https://code.google.com/u/104503330167604998880/) on April 05, 2010 17:22:21_

I concur, this is a really important improvement/feature. But it is not absolutely required for Beta1 release.

I think it is among the top five to address after the Beta1 critical issues are fixed.

**Comment by carueda** [comment]
Do we really want this?  I agree it would be a nice-to-have, but I think users would be better off with some of the many issue tracker options out there to support the development/improvement of artifacts like  ontology files.  Perhaps just include some (optional) metadata property to capture where the associated issue tracker is located?

**Comment by graybeal** [comment]
I agree, it is nice to have but not essential, and it would be hard to implement well in a short period of time. And BioPortal hasn't had good uptake on their similar feature, so it isn't automatically of great value. 

Pointing to a separate project issue list would be a very nice feature instead. 

Ideally someday we could get the number of open issues for a given ontology project, and display it in ORR. But not today.

Changed priorities accordingly.

**Comment by graybeal** [comment]
Do we need to create a new issue or can we continue tracking here?

**Comment by carueda** [comment]
Let's close this (as it was very specific about a proper issue tracker in the ORR system), and open a new one about just capturing a pointer to an associated issue tracker.

**Comment by graybeal** [comment]
OK, created #382 and am closing this.
