### ISSUE TITLE
Deprecate a term

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#233]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 13, 2009 15:45:17_

[from JG's 2009-12-04 email] 

What capability do you want added or improved? 
API to deprecate a term. (well, this capability can also be provided in the
ORR portal) 

Where do you want this capability to be accessible? 
In the main ORR service 

What sort of input/command mechanism do you want? 
An HTTP POST call where I can provide: 
- username/password
- Ontology URI
- the URI of the term to be deprecated
- optionally, URI of the term that should be used instead 

What is the desired output (content, format, location)? 
A textual response (perhaps in XML) indicating the result of the operation:
i) success, confirming the deprecation; deprecated term URI; and URI of the
term that should be used (if given); ii) error, including the reason of the
error. 

Other details of your desired capability? 

0) Similarly as with issue #232 (modification of a term), the deprecation
of an existing term does seem to require the creation of a new version of
the vocabulary.

1) An HTML form should be included to illustrate the required information
(and demonstrate the functionality). 

2) A programmatic example (in java) showing how to use the service.

See related: issue #232 , issue #231 , issue #214

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=233_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 05, 2010 17:34:49_

(bulk edit): REmoved Beta1 label per discussion today (John and Carlos)

**Labels:** -Milestone-Beta1

**Comment by carueda** [comment]
https://github.com/mmisw/orr-ont/issues/36 (modifying a term includes the possibility of declaring deprecated -- in whatever way this turns out to be implemented)
