### ISSUE TITLE
ontology metadata properties not used properly.

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#235]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 21, 2009 11:26:49_

All metadata properties are handled as datatype properties. For example,
omv:hasCreator is an object property with domain Ontology and range omv:Party. 

A consequence of this erroneous mechanism is making ontologies that are
OWL-DL to become non-OWL-DL. Attached is one such ontology (the MMI Device
ontology). I tested this with the http://www.mygrid.org.uk/OWL/Validator What needs to be done: Properly use the properties that are object
properties, creating the necessary object instances.

**Attachment:** [device.owl](http://code.google.com/p/mmisw/issues/detail?id=235)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=235_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 13, 2010 12:08:57_

Luis thinks is not needed for beta1

**Labels:** -Milestone-Beta1

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/94
