### ISSUE TITLE
Cannot register new version of ontology

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#237]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 10:46:15_

[from M. Compton's email]

I tried to update the ontology in the MMI repository [...] but I can't seem
to upload the new version.  If I
download the ontology that's at MMI, alter it and try to reload it
fails at the first step because the URI is wrong.  If I try and upload
the one I had already locally it lets me get right through to the
final stage, but then says that the URI is wrong.

(attached is the version made by downloading from MMI

**Attachment:** [SensorBasis.owl](http://code.google.com/p/mmisw/issues/detail?id=237)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=237_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 10:55:48_

First observation: the email says "attached is the version made by downloading from
MMI" but it seems that's not the case because the attached file does not contain any
owl:Ontology resource, which is created my MMI ORR when the ontology is registered.

I'll be looking into this more closely later.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 16:31:33_

Examining the issue:

1) The URI of the registration: http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl 2) This is dispatched just fine: http://mmisw.org/orr/#http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl 3) Some of the contents of the registered ontology (unversioned request):

  \<rdf:RDF
    xmlns:rdf=" http://www.w3.org/1999/02/22-rdf-syntax-ns# "
    xmlns:omvmmi=" http://mmisw.org/ont/mmi/20081020/ontologyMetadata/ "
    xmlns:xsd=" http://www.w3.org/2001/XMLSchema# "
    xmlns:rdfs=" http://www.w3.org/2000/01/rdf-schema# "
    xmlns:owl=" http://www.w3.org/2002/07/owl# "
    xmlns=" http://www.w3.org/2009/SSN-XG/Ontologies/ "
    xmlns:omv=" http://omv.ontoware.org/2005/05/ontology# "
    xmlns:dc=" http://purl.org/dc/elements/1.1/ "
    xml:base=" http://www.w3.org/2009/SSN-XG/Ontologies ">
    \<owl:Ontology rdf:about="">
        ...
        \<omv:uri> http://www.w3.org/2009/SSN-XG/Ontologies</omv:uri> ...
   \</owl:Ontology
   \<owl:Class
rdf:about=" http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#Process ">
        \<rdfs:subClassOf>
            \<owl:Class
rdf:about=" http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl#System"/ >
        \</rdfs:subClassOf>
    \</owl:Class>
    ...
  \</rdf:RDF>



4) but note that the request for the versioned ontology gives:

  \<rdf:RDF
    xmlns:rdf=" http://www.w3.org/1999/02/22-rdf-syntax-ns# "
    xmlns:j.0=" http://mmisw.org/ont/mmi/20081020/ontologyMetadata/ "
    xmlns:owl=" http://www.w3.org/2002/07/owl# "
    xmlns:j.1=" http://omv.ontoware.org/2005/05/ontology# "
    xmlns:dc=" http://purl.org/dc/elements/1.1/ ">
    \<owl:Ontology rdf:about=" http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl ">
        ...
    \</owl:Ontology>

---- Note: No contents here ----

  \</rdf:RDF>

**Status:** Started  
  **Cc:** -bermud

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 30, 2010 15:50:46_

[from Michael Compton's Jan 7 2010 email]

Carlos,

The attached file I produced by downloading the current version from the MMI
repository and making a few small changes.  If I attempt to upload it it complains
(at the file load stage) that the ontology has the base URI http://www.w3.org/2009/SSN-XG/Ontologies instead of http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl which is true and seems to indicate a problem in that I can't even download and then
reupload the same ontology.

If I edit the ontology to have the correct URI, I can get through to the final stage,
but on pressing finish I get the message:

The new base URI ( http://www.w3.org/2009/SSN-XG/Ontologies ) is not equal to the
registered base URI ( http://www.w3.org/2009/SSN-XG/Ontologies/SensorBasis.owl ) 

Which is again strange because the ontology then does have the correct URI.

Thanks
Michael

**Attachment:** [SensorBasis.owl](http://code.google.com/p/mmisw/issues/detail?id=237#hc4)

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 13, 2010 12:05:47_

**Status:** NeedMoreInfo  
  **Labels:** -Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 25, 2010 23:19:02_

Luis and I agreed that this is not a showstopper and decided to remove the beta1
label.  Now, also lowering priority to normal.

**Labels:** -Priority-Critical Priority-Medium

**Comment by carueda** [comment]
Very old and rather obsolete issue (the referred ontology is not even registered), so closing as WontFix.
