### ISSUE TITLE
preserve column order

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#240]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 22, 2010 13:54:43_

What capability do you want added or improved? Display vocabulary with the same order of columns as I used when creating
the vocabulary. Where do you want this capability to be accessible? In the 'voc2rdf' style of displaying a vocabulary What sort of input/command mechanism do you want? none What is the desired output (content, format, location)? columns is the same order as that of definition time Other details of your desired capability? In general, order is not important for the contents of the knowledge
captured in the ontology (unless it's explicitly captured as part of the
information).  Although keeping the order is convenient for the user
interface, typical libraries do not specify any order in which the ontology
elements will be retrieved; in particular, it is not guaranteed that the
elements will be reported in the same order as they were inserted at
creation time.  I have spent some time to come up with some workaround but
it is not implemented yet. What version of the product are you using? MMI Portal 1.8.1.alpha (20091229171344)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=240_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 02, 2010 11:24:47_

USing an index might be an approach, http://www.topquadrant.com/topbraid/2007/05/composite.owl ( http://composing-the-semantic-web.blogspot.com/2007/07/composite-design-pattern-in-rdfowl.html )

**Comment by mmisw** [comment]
_From [steph_wa...@consolidated.net](https://code.google.com/u/112846428158176258467/) on June 14, 2010 12:51:19_

I think it would be helpful for the users to view the columns in the appropriate order.  One of the functions of the ORR is to give users the ability to view existing vocabularies/ontologies to see if they need to build a new one/edit one, etc.  Having the columns in a more logical order would greatly assist this.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 15, 2010 14:11:37_

Not sure what you mean by "logical order."  Wouldn't preserving the original column order indicated by the user be enough?

**Comment by carueda** [comment]
Implemented in v3.
