### ISSUE TITLE
watchdog: capture parameters

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#250]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 28, 2010 21:50:15_

What capability do you want added or improved? capture parameters in a more flexible in the watchdog programs https://code.google.com/p/mmisw/source/browse/#svn/trunk/org.mmisw.watchdog

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=250_

**Comment by carueda** [comment]
the mentioned "watchdog" program has long been obsoleted by the new efforts:

https://github.com/mmisw/cf2rdf
https://github.com/mmisw/udunits2rdf
