### ISSUE TITLE
Change acronym without submitting a new ontology

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#254]
_From [steph_wa...@consolidated.net](https://code.google.com/u/112846428158176258467/) on June 14, 2010 12:48:47_

What capability do you want added or improved? 
A way to change the acronym in the metadata without having to submit a new ontology (otherwise, you can end up with 2 files in the repository that differ only in their acronym (and, thus, url) 

Where do you want this capability to be accessible? 
Edit new version 

What sort of input/command mechanism do you want? 
ability to change and update button 

What is the desired output (content, format, location)? 
new acronym, new url 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.) 

I'm trying to update acronym field in the metadata (and thus, the URL) of the IOOS Parameter Vocabulary without having to submit another file.  I don't want two versions of this vocabulary in the ORR.  If there is no way for the owner to change it, can you change it, Carlos?

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=254_

**Comment by carueda** [comment]
Closing as wont' fix --  there's no such acronym-determining-the-uri mechanism in new ORR3.
