### ISSUE TITLE
reset password in effect but lost if error while sending email

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#258]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 17, 2010 15:50:47_

If the setup of the internal email account details (for sending password-related messages) is incorrect, the following misbehavior will occur when a user selects "reset password": the password is actually reset but the sending of the email to the user will fail, so the user won't get the new password.

See Server.resetUserPassword(String username).

Using MMI Portal 1.9.4.alpha (20100617134902)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=258_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 17, 2010 16:43:56_

Server.resetUserPassword: Part of the fix is to first check that the mail account parameters are given.
This part is now implemented. Module iserver version 1.9.4.alpha

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 21, 2010 14:25:27_

**Labels:** -Priority-Medium Priority-Low

**Comment by carueda** [comment]
v.2.5.9 (201511242246)

Additional handling including a message like "please try again later ..if the problem persists contact the administrator." But note that the likely problem is actually from inappropriate configuration.

<img width="300" alt="2015-11-24_2024" src="https://cloud.githubusercontent.com/assets/556505/11388647/4cac3628-92ed-11e5-8827-37942331d89a.png">
