### ISSUE TITLE
Direct registration in fully-hosted mode

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#262]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on July 25, 2010 09:08:25_

What capability do you want added or improved? 
Direct registration in fully-hosted mode 

Where do you want this capability to be accessible? 
`http:.../orr/direg`  as is currently the case 

Other details of your desired capability? 
Direct registration is currently supported but only for the re-hosted mode. This request is about supporting fully-hosted as well. 

What version of the product are you using? 
MMI Portal 1.9.8.alpha (20100630223813)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=262_

**Comment by carueda** [comment]
Fully supported by new backend in v3 (where BTW there's no intrinsic need at all for the distinction between fully- or re-hosted submission)
