### ISSUE TITLE
Evaluate and determine front-end framework selection for overhauled portal (was: Upgrade GWT to most recent version)

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#268]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 02, 2010 00:59:57_

The ORR portal currently uses GWT 1.5.2, which has been pretty stable but this version is becoming very old compared with the many new versions and improvements in that toolkit (current version is 2.0.4). The upgrade is not as straightforward(*) and requires some careful attention and testing, but is worth doing it to make possible various enhacements to ORR itself.

(*) GWT 1.6 introduced some important changes (diff directory structure, new even handler interfaces, etc)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=268_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 25, 2010 17:07:53_

Upgrade to GWT 2.0.4 (latest at time of writing) was tried and evaluated.
See details at http://mmisw.googlecode.com/svn/trunk/org.mmisw.orrportal/gwt2/gwt2.txt In summary, this preliminary exercise was partially successful:

- The new development mode is NOTICEABLY SLOWER than the 1.5.2 hosted mode!

- The new production mode runs certainly much faster than development mode, but SLOWER than the 1.5.2 production mode, although perhaps acceptable when not dealing with big ontologies (like CF).

Presumably 2.0.4 must be better in several aspects, but definitely NOT in performance (at least with the default settings)!  This is frustrating; I was expecting only improvements (or at least not degradations on any sort) by just upgrading  :-(

A conclusion at this moment: decide on the upgrade as we address the core performance issues we have in general ( https://code.google.com/p/mmisw/issues/list?can=2&q=label=Performance ). Interestingly, some of these issues may be easier to solve with the added functionality in terms of GUI widget that can be enabled by upgrading!

**Status:** Diagnosed

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 18, 2012 14:12:57_

Additional tests with latest GWT 2.4.0

- Various tests with the current widgets seem to work fine with GWT 2.4.0. But more exhaustive tests are needed before switching to it. 

- Note the GWT 2.4.0 no longer supports quirks mode. But enabling standards mode seems to not cause any really issues to the interface. (Besides, better to fully engage in standard mode ;)

- Some preliminary tests with a new table implementation based on new GWT 2.4.0 widgets, pretty successful but not complete yet. The plan is to use some if the new widgets to improve the usability of the ORR, in particular, data entry in the voc2rdf interface.

More details: https://code.google.com/p/mmisw/source/browse/trunk/org.mmisw.orrportal/gwt2/gwt2.txt In summary, good progress but work still remains.

**Labels:** Usability

**Comment by carueda** [comment]
Renaming entry to "Evaluate and determine front-end framework selection for overhauled portal" as a more general task; in particular to consider not only GWT but also other potential alternatives.
