### ISSUE TITLE
incorrect export to CSV

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#269]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 03, 2010 10:32:23_

What steps will reproduce the problem? 
1. edit a vocabulary table in the ORR (the so called voc2rdf interface)
2. include commas (or any of the supported separators for export to CSV) in some cell 
3. select Export 

What is the expected output? 
Properly formatted CSV, in particular with my commas being escaped 

What do you see instead? 
malformed CSV

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=269_

**Comment by carueda** [comment]
Closely related: #121

**Comment by carueda** [comment]
Not an issue in v3.
