### ISSUE TITLE
CSV with record spanning multiple lines

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#274]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 16, 2010 14:19:45_

What steps will reproduce the problem? 
1. import CSV contents with a record spanning more than one line 

What is the expected output? 
Proper parsing of the multi-line record. 

What do you see instead? 
2nd and later lines in the record being incorrectly handled as other records

Note: there have been other issues here related with the limited support for CSV.  This is just one more.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=274_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 16, 2010 14:31:30_

**Labels:** -Priority-Medium Priority-High

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on May 30, 2011 11:48:31_

(re-tagged as enhancement upon general revision of current issues)

**Labels:** -Type-Defect Type-Enhancement

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 25, 2012 08:45:54_

**Labels:** -Priority-High Priority-Medium

**Comment by carueda** [comment]
Fixed in v3.
