### ISSUE TITLE
improve handling of "testing" submissions

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#279]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on September 03, 2010 16:03:32_

Currently the special authorities "testing" and "mmitest" (and perhaps one or two more), are used as indicators that the ontology is to be considered for "testing" purposes.  The effect of this is that a testing ontology shows up in the list of ontologies only for the submitter (and the admin).  There are some known issues and enhancement requests around this, see issue `#200` and issue `#246` .

The request here is specifically about using a different mechanism to tag ontologies as "testing", in particular, NOT using the authority fragment of the URI.  Note that a single authority, say "ioos", may have some "testing" ontologies registered.

The proposal is to have an explicit option so the user can indicate that a submission is to be considered "draft" or "testing."  Internally this could be reflected in the metadata associated with the ontology, using some appropriate vocabulary. Possible vocabs include: http://www.w3.org/2003/06/sw-vocab-status/note.html NOTE: this should be part of a more general handling of multiple possible status categories (draft, testing, unstable, experimental, approved, stable, etc).

(Another related aspect: "visibility", eg., allow to indicate "only visible to me", "only visible to X group", "public", ...)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=279_

**Comment by mmisw** [comment]
_From [john.gra...@marinexplore.com](https://code.google.com/u/105680068996922490555/) on May 13, 2013 16:40:45_

An advanced feature is to enable which of the draft versions could be enabled for a certain inference calculation, maybe in place of the current version. This would allow testing of changes to ontologies.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 17, 2014 12:31:19_

An internal mechanism (with direct setting in the underlying database) has been implemented to explicitly mark entries as "testing."  The default behavior continues to be based on the authority fragment in the ontology URI. 

ORR Portal 2.0.5 (201406171128)
MMI Ontology and Term URI Resolver  2.0.5 (201406171337)

**Status:** Started  
  **Cc:** grayb...@marinemetadata.org  
  **Labels:** -portal mmiorr ont

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on June 17, 2014 13:07:06_

Whoa, that is way cool Carlos. Thanks!

**Comment by carueda** [comment]
Overall handling much improved in v3.
