### ISSUE TITLE
Support for subClassOf in csv

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#285]
_From [mike.e.b...@gmail.com](https://code.google.com/u/104806978225310943594/) on October 11, 2010 09:18:04_

What capability do you want added or improved? 
To have a predefined label in my CSV file which would be interpreted by the importer as a subClassOf indicator. 

Where do you want this capability to be accessible? 
voc2rdf, voc2skos 

What is the desired output (content, format, location)? 
The value within the CSV labeled subClassOf would be inserted into a subClassOf property of the term.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=285_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 10:18:39_

See also issue #110 .

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/89
