### ISSUE TITLE
Supporting Authority Approval "Bumper Stickers"

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#286]
_From [mike.e.b...@gmail.com](https://code.google.com/u/104806978225310943594/) on October 11, 2010 09:30:01_

We should somehow encourage the stated approval from authoritative bodies (IOOS, Qartoc, OGC, NMMO, NOAA, etc) of full ontologies or individual terms. Then the potential user of a term can determine how strong that term is within their community.

Not being as Ontology savvy as I need to be, I don't know the best approach, whether it be through a predefined property in a class or through mappings between terms and the authority ("approved by") using VINE, etc.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=286_

**Comment by carueda** [comment]
Related: #279

**Comment by carueda** [comment]
@mikebotts FYI

Closing as Addressed_in_ORR3, because that new version provides significantly improved support for **status**, **visibility**, and **organizations**., which seem to cover the most practical aspects of this suggestion.  (If not, new issues can be entered under relevant ORR3 tracker.)
