### ISSUE TITLE
grant permission to edit to other users

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#291]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 24, 2011 14:27:32_

What capability do you want added or improved? (from Sara's email) A way to provide other registered users to have permission to edit (err ... create new vocabs with edits) vocabs Where do you want this capability to be accessible? What sort of input/command mechanism do you want? What is the desired output (content, format, location)? Other details of your desired capability? What version of the product are you using? ORR Portal 2.0.17.beta (201103301508)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=291_

**Comment by carueda** [comment]
This will be covered in the new ORR3 system with its organization feature: owned by an organization, a registered ontology can be edited by any of the corresponding organization members.

**Comment by carueda** [comment]
Implemented in ORR3
