### ISSUE TITLE
Add a comments section to ontology display

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#305]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 14, 2013 18:42:19_

What capability do you want added or improved? 
Add a comment service (like disqus.com) so users can comment around entries in the repository. 

Where do you want this capability to be accessible? 
When displaying an ontology in the portal. Probably a button to expand the comment section. 

What sort of input/command mechanism do you want? 
Visitors are able to review current comment thread and also to reply or add new comments. 
It should be possible to associate moderator(s) to the particular thread, in principle, the ontology submitter would be the moderator, and/or there is some mechanism by which the submitter can indicate the moderator(s).

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=305_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 14, 2013 19:00:54_

interesting:
 - http://cssdeck.com/post/9/why-we-moved-from-disqus-to-custom-commenting-system

**Comment by carueda** [comment]
Simply won't fix.
