### ISSUE TITLE
VINE check-boxes can be jump-boxes

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#312]
_From [grayb...@marinemetadata.org](https://code.google.com/u/100453653739559568016/) on April 01, 2013 05:32:23_

What steps will reproduce the problem? 
1. Go to perform a mapping in VINE. Create a mapping or two.
2. (Possibly have to do some intermediate step before this behavior occurs)
3. Check on a box to the left of one of the mappings. 

What is the expected output/behavior?
 Box should become checked.

 What do you see instead? 
Window jumps up to a higher part of the page, and box remains unchecked. 

"Select All" makes the boxes active again. 

What version of the product are you using? (You can see the version in the lower left corner of the ORR page.)
 ORR Portal 2.0.42.beta (201302221022) 

If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.).

 If possible and relevant, please provide a screen shot showing the problem. Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=312_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 08, 2013 18:57:20_

Couldn't reproduce.  Perhaps I'm misunderstanding your steps.

**Comment by carueda** [comment]
Tried again and cannot reproduce (tried with Chrome, Firefox, and Safari).
