### ISSUE TITLE
leaving page with edited mappings causes them to be lost

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#315]
_From [john.gra...@marinexplore.com](https://code.google.com/u/105680068996922490555/) on April 17, 2013 14:44:44_

What steps will reproduce the problem? 
1. Go to produce or edit a mapping
2. Create new mappings, without saving
3. Navigate back to a previous page in the browser 

What is the expected output/behavior? 
Somehow, some way, the mappings should not be lost; either prompt the user "do you really want to leave this page?", or save the mappings as a temp file and offer to restore them on revisiting the mapping. 

What do you see instead? 
Mappings are lost. Going forward in the browser to the original page makes it reload (mapping) ontology. 

What version of the product are you using? (You can see the version at the bottom of the ORR page.) ORR Portal 2.0.42.beta (201302221022) 

If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.). 
http://mmisw.org/ont/mx_testing/mxparms1map 

If possible and relevant, please provide a screen shot showing the problem. 

Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc. 
Chrome, recent. (Actually Iron, but it's based on Chrome.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=315_

**Comment by carueda** [comment]
Just reproduced this issue with v2.5.7.
BTW, the issue also happens with the vocabulary editor ("voc2rdf").

**Comment by carueda** [comment]
Fixed as of v2.5.9 (201511241709).

The user is now prompted to confirm abandoning the editing or upload operation upon change in the browser history.

Also, a similar confirmation when trying to close the browser window or tab was missing for upload operations; this has been fixed as well.
