### ISSUE TITLE
linked-csv

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#316]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 24, 2013 20:28:10_

Investigate how to leverage/integrate/align with http://jenit.github.io/linked-csv/ in the vocabulary tool and as an output format.

(thanks Matt J. via developers@dataone.org mailing list for the interesting links, the other one being http://blog.okfn.org/2013/04/24/frictionless-data-making-it-radically-easier-to-get-stuff-done-with-data/ )

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=316_

**Comment by carueda** [comment]
Closing as "won't fix". If really needed, open issue in relevant new ORR3 repo.
