### ISSUE TITLE
URI with extension (*.something) not resolved

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#318]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 13, 2013 09:35:18_

What steps will reproduce the problem? 
1. Try to resolve http://mmisw.org/ont/testing/GeoNames/H.RSV (which does exist in the repo) 

What is the expected output?
Usual resolution  as with any other registered ontology or term URI 

What do you see instead? 
HTTP Status 400 - output format not recognized: rsv

Using MMI Ontology and Term URI Resolver 2.0.43 (201310112351)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=318_

**Comment by carueda** [comment]
Not an issue in v3.

See the following (where v3 is still deployed on a temporary location, `/ont3/`):

![image](https://cloud.githubusercontent.com/assets/556505/18234391/78c75d86-72b8-11e6-8d1c-1f0a5d396fbc.png)

**Comment by carueda** [comment]
Just re-verifying this with the recently upgraded MMI ORR instance to v3:

http://mmisw.org/ont/testing/GeoNames/H.RSV

![image](https://cloud.githubusercontent.com/assets/556505/26600621/a3767624-4531-11e7-9a10-4fc01e89fe81.png)

**Comment by graybeal** [comment]
I believe that periods are not legal in URIs.

**Comment by carueda** [comment]
And your point is?

**Comment by fgayanilo** [comment]
RFC 1738 or 3986 does not prohibit the use of a period. A period or decimal digit is identified as “unreserved” character – I may be wrong but had been using it. F
