### ISSUE TITLE
IE9 doesn't show contents

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#319]
_From [john.gra...@marinexplore.com](https://code.google.com/u/105680068996922490555/) on November 27, 2013 08:20:06_

What steps will reproduce the problem? 1. Use IE9 on PC.
2. Go to http://mmisw.org/ont/bodc/NVSDevicesToTRDIOntology 3. When you click on 'Contents' nothing appears. Works OK in Chrome and Firefox. What is the expected output/behavior? List of terms. What do you see instead? Nothing. What version of the product are you using? (You can see the version at the bottom of the ORR page.) If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.). http://mmisw.org/ont/bodc/MapSeaVoxPlatforms2IOOSandRDIPlatforms http://mmisw.org/ont/bodc/NVSDevicesToTRDIOntology If possible and relevant, please provide a screen shot showing the problem. Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc. IE9

Reported by Roy Lowry.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=319_

**Comment by mmisw** [comment]
_From [grayb...@marinemetadata.org](https://code.google.com/u/100453653739559568016/) on November 27, 2013 08:24:45_

Minimum action (after duplicating this issue) is to document it in the manual and on the front page of the site, if fixing it is too messy.

**Labels:** -Priority-Medium Priority-High OpSys-Windows

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 27, 2013 10:25:56_

I just reproduced the (mis)behavior, unfortunately with IE10 so it seems IE is simply not well supported. It would probably be better supported with an update of the underlying Google Web Toolkit, but this would take some significant effort given the many and non-trivial changes in that toolkit (see issue `#268` ).

I updated https://marinemetadata.org/orrstatus .  Feel free to adjust as needed.

**Status:** Accepted  
  **Labels:** Usability

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 03, 2014 20:57:41_

I'm expecting the display will much better with this prototype: http://mmisw.org/experimental/orrv/#/uri/http://mmisw.org/ont/bodc/NVSDevicesToTRDIOntology whose underlying technology is a strong candidate for overhauling the UI.
Will try this when I get access to a PC, but let me know how it goes for you.

**Cc:** grayb...@marinemetadata.org

**Comment by carueda** [comment]
Should not be an issue in v3.  (If so, submit issue in the new orr-portal repo.)
