### ISSUE TITLE
recover account info with email

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#322]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on June 26, 2014 10:18:35_

What capability do you want added or improved? 
Ability to recover my account info by providing my email. 

Where do you want this capability to be accessible? 
Along with the "forgot password" button, include a "forgot username" action where I can enter my email address 

What version of the product are you using? 
ORR Portal 2.1.0

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=322_

**Comment by carueda** [comment]
Implemented in v3.
