### ISSUE TITLE
Nicely display multiple classes in ORR

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#324]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:19:33_

What steps will reproduce the problem? 
1. Display any ontology with individuals in multiple classes, e.g., http://mmisw.org/orr/#http://mmisw.org/ont/mmi/udunits2-common 
2. Click on Individual drop-down selector, and scroll through list until reaching UnitNames type individuals 3. 

What is the expected output/behavior? 
I want individuals from each class listed in a table specifically for that class. 

What do you see instead? 
The existing layout has lots of blank columns, because it is blending individuals of two different Classes 

What version of the product are you using? (You can see the version at the bottom of the ORR page.) ORR Portal 2.1.0 (201406180055) 

If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.). 

If possible and relevant, please provide a screen shot showing the problem. Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=324_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:24:50_

See also issue #114 .

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:58:20_

An example of what this might look like (from J Bosch) is Mike Bott's PrettyView. See http://q2o.whoi.edu/node/129 , toward the bottom there are some links to PrettyView content. (Used for SensorML data in his case.)

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 12:01:00_

Also a link to one of the examples: http://sensors.ws/SensorMLforms/PrettyView?url=http://mvcodata.whoi.edu/downloads/sensorML/v1.0/examples/sensors/ADCP_2.2/ADCP_System.xml And to the PrettyView front end: http://www.sensors.ws/SensorMLforms/upload.jsp

**Comment by carueda** [comment]
The `sensors.ws` site is not what used to be anymore. If you could provide other references or a mockup that would help.

**Comment by graybeal** [comment]
The page at http://www.sensorml.com/SensorMLforms/PrettyView?url=http://mvcodata.whoi.edu/downloads/sensorML/v1.0/examples/sensors/ADCP_2.2/ADCP_System.xml is still an active example, that is sufficient for this purpose. I've copied a graphic corresponding to this URL.

The point is that each table shows one type of class, and only the columns necessary to display that class. 

<img width="1528" alt="screen shot 2015-12-14 at 8 51 42 pm" src="https://cloud.githubusercontent.com/assets/1266896/11802352/aaae0208-a2a4-11e5-87ab-2cf48db3ab35.png">

**Comment by carueda** [comment]
Fixed in v3.
