### ISSUE TITLE
Nicer LOD-friendly display of content on ontology page

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#326]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:48:20_

What capability do you want added or improved?

 I want to improve the display of the ontology and metadata (see also issue #146 and issue #327 ), particularly values shown within the table. First priority is to provide auto-recognition of things that can be linked:
A) URLs within the ontology auto-linked
B) URLs elsewhere auto-linked
C) Codes or Terms within the ontology auto-linked, to resolve on the appropriate ORR term page (see other details below) 

What is the desired output (content, format, location)? 

Following CFSN format 

Other details of your desired capability? 

Later it would be cool to do CFSN's _ term recognition for searching, but recognizing more types of terms:
- ASCII linked by _
- ASCII with embedded camelCase
- ASCII preceded by _
- hex IDs: 6 or more hex digits in a row 

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=326_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:48:47_

**Owner:** ---

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:54:32_

Meant to say, before (A) in the list above, 
0) Link classes and terms to their page in ORR

**Labels:** mmiorr

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 07, 2014 22:59:08_

What does LOD stand for?

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on October 08, 2014 09:55:00_

Linked Open Data

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/92
