### ISSUE TITLE
improved LOD presentation of term page

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#327]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:52:59_

What capability do you want added or improved? I want to improve the display of terms in ORR (see also issue #326 ), particularly values shown within the table. First priority is to provide auto-recognition of things that can be linked:
A) Link back to the parent ontology
B) URLs within the parent ontology auto-linked
C) URLs elsewhere auto-linked (different color)
D) Codes or Terms that are within the parent ontology auto-linked, to resolve on the appropriate ORR term page (see other details below)

Second priority is to add known mappings, as CFSN does. Where do you want this capability to be accessible? Each term page What sort of input/command mechanism do you want? What is the desired output (content, format, location)? Following CFSN format Other details of your desired capability? Later it would be cool to do CFSN's _ term recognition for searching, but recognizing more types of terms:
- ASCII linked by _
- ASCII with embedded camelCase
- ASCII preceded by _
- hex IDs: 6 or more hex digits in a row What version of the product are you using? Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=327_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 12:04:58_

**Owner:** ---

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 22, 2014 12:09:52_

Not yet documented and still work in progress but the generic engine that enables CFSN is being refactored here: https://github.com/mmisw/scv (I likely will be renaming this to vocbrowser, or vrowser, or ...).  Besides facilitating the customization of the browser to a particular vocabulary (like in cfsn) but end users, the idea is to also automatically dispatch vocabularies at the ORR with the new interface.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 22, 2014 13:40:03_

Mentioned repo just renamed to https://github.com/mmisw/vrowser Some experimental deployments:

- http://mmisw.org/experimental/vrowser/ioos_param/ - http://mmisw.org/experimental/vrowser/ooi_epe_science/ - http://mmisw.org/experimental/vrowser/cf/

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 07, 2014 20:50:24_

just to note that the mentioned repo was later on renamed to https://github.com/mmisw/vbrowser And the experimental deployments:

- http://mmisw.org/experimental/vbrowser/ioos_param/ - http://mmisw.org/experimental/vbrowser/ooi_epe_science/ - http://mmisw.org/experimental/vbrowser/cf/

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on October 07, 2014 22:57:32_

That last one should be
- http://mmisw.org/experimental/vbrowser/cfsn/

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/88
