### ISSUE TITLE
Improved ORR ontology page search capability

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#328]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 12:04:13_

What capability do you want added or improved? 
Add search features to ORR  comparable to those in CFSN. 

Where do you want this capability to be accessible? 
when viewing an ontology page. 

What sort of input/command mechanism do you want? 
As in CFSN, an overall search that searches everywhere, and a per-column search that searches only within that column.

Ideally GLOB or REGEX searching available for all cases. 

What is the desired output (content, format, location)? 
One sees only the subset of terms that have been searched for.

 Other details of your desired capability? 
Hide the search windows until they are needed (uncover with a looking glass icon or similar).

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=328_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 12:04:27_

**Owner:** ---

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/87
