### ISSUE TITLE
migrate mmisw to GitHub

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#332]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on October 08, 2014 11:01:20_

What capability do you want added or improved? Move the code and issues for mmisw to the GitHub system.

Steps for code:

Review https://help.github.com/articles/importing-from-subversion/ our google code is basically in only one repository "mmisw".  The trunk is https://code.google.com/p/mmisw/source/browse/#svn&#37;2Ftrunk , under which all of our different projects or modules are located)
import each of the main projects under that repo as a corresponding github repo, for example, the project at https://code.google.com/p/mmisw/source/browse/#svn&#37;2Ftrunk&#37;2Forg.mmisw.ont would go to a repo https://github.com/mmisw/ont Test functionality of resulting builds

Steps for issues:

google for possible approaches to (pseudo)automatically migrate from a google issue tracker 

Steps for both:

Update pages on MMI and mmisw.org that point to the repository. Other details of your desired capability? All existing issues migrated. Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=332_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on October 08, 2014 11:25:45_

Looks like this is the trick for issues: https://github.com/arthur-debert/google-code-issues-migrator but it's non-trivial enough that we should read this: http://beets.radbox.org/blog/github-issues.html

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 08, 2014 10:41:31_

Code migrated as described at https://github.com/mmisw/miscn/wiki/svn-git-migration

**Status:** Started

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on January 19, 2015 21:36:52_

I've downloaded the issue migration software and started testing it on https://github.com/graybeal/ont .  It's a bit squirrelly but I think usable. You can see the results so far at https://github.com/graybeal/ont/issues?q=is%3Aissue .

(At the moment I'm a bit stuck because GitHub has some kind of rate limiter in place. I have a support request in. Won't be a show-stopper.)

Problems that I hope are of no concern:
 - All the issues and comments metadata will show as created when the script is run. (Internal header shows correct info.)
 - All the issues and comments metadata will show as created by me. (Internal header shows correct info.)
 - GitHub issues page only shows about 20 at once. This makes it hard to see all of the issues, even just all of the open issues.

Problems I plan to address:
 - I will assign the assignee manually to match the original; with group assignments it should be manageable. (Though, not sure why the code isn't assigning this field correctly.)
 - There is something funky that causes extra issues to be generated when they shouldn't be. I think I can resolve or work around this.

Do you see any other problems?

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on January 19, 2015 21:52:41_

Additional gotchas:

When we do it for real, watchers will get a lot of email notifications. I will send them email a day before I start, asking if they want to not follow us for a day, while the migration takes place.

Note: If you want to have owner privileges on the issues and comments, which lets you change their text, we could have you run the import (or give me your password to run it) -- then all the issues will have your name instead of mine.

One more possible concern: I'm loading all the issues into ont. Some of them are arguably not relevant to ont. since you can't delete issues, if this is a significant concern, let me know -- but I'm not sure what I can reasonably do about it. (There are tools that can 'migrate' issues between repositories by copying them and closing the original. Or I could customize the python script, might take a day or two....

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 20, 2015 20:27:57_

Too bad that there is not a more straightforward mechanism to transfer the issue information from google code to github, including at least original dates and perhaps with just a minor effort in terms of authorship mappings (thinking a la svn-to-git migration, which allows for such nice things)..

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on January 21, 2015 00:19:02_

I've successfully migrated all the issues to the test repository https://github.com/graybeal/ont . You can see the results at https://github.com/graybeal/ont/issues . 

Please check it out to see if it is acceptable. I only assigned the first 3 tabs (issues 1 to 75) to assignees (I assume owner -> assignee), and only for you, me, and Paul. 

Let me know if you saw any notifications of the assignments -- I did not get any myself. (Odd, that, given that we are all watchers of the repository.)

I think I can manually assign all the issues in the final repository in about an hour, so that will be faster than automating the process.

Other than the previously noted concerns, and even allowing for them, it all looks workable to me. 

Re comment `#5`, I haven't looked at the API but have assumed it is impossible to set the issue metadata for date/time and author. I'll take a brief look before proceeding, but if you find out differently I'll modify the script to take advantage.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 21, 2015 05:14:17_

Good job!

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 21, 2015 05:54:05_

Although I initially suggested that we created separate git repos for the various projects under https://code.google.com/p/mmisw/source/browse/#svn%2Ftrunk (and we already made those individual migrations), seems like a better approach would have actually been to:

a) import the whole mmisw code into a single git repo
b) then migrate the whole set of issues to that single repo (in particular, not needing to split the issues depending on the particular sub-project)

For a) I just used the github importer feature and, for the moment, created the resulting repo under marinemetadata: https://github.com/marinemetadata/mmisw , but if we decide this is actually a better approach, we can repeat this to have it under mmisw .

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on January 21, 2015 10:44:28_

Since we haven't hooked up telephonically, here are some thoughts.

- I don't think the issues organization should drive the repository organization, that's the tail wagging the dog.
- Just looking at the top level of mmisw and marinemetadata repositories, the mmisw presentation feels much cleaner. 
  -- Having each project in its own GH project seems more consistent with GitHub practice & design
  -- Seeing each mmisw project as a separate project with a name (ont, cfsn, etc.) is much more user-friendly
  -- Using a particular project doesn't carry the overhead of the whole set of projects

The issues are all bundled together now. That's a problem with the issues, whether or not the projects are kept together. So why are the issues like that -- is it because the projects are so closely related that it's hard to decide which projects an issue affects, or that they often affect multiple projects (in which case keeping all issues together is OK no matter where the projects live)? Or just a function of where the issues were maintained or how they were tagged (or not tagged)?  Whatever caused that problem, it has to be fixed by having a clear division of projects, and dealing with each issue to tag it (or maybe move it) to its appropriate project(s).

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 21, 2015 10:58:44_

I'm not proposing this single-mmisw-repo approach just for the sake of easing the issue import.  Actually I was more thinking in terms of capturing the "legacy" MMI ORR software (yeah, it is actually not "legacy" because it is still the current one ;)  in a single,  *separated* repo in Github.  All those other more recent efforts (orr-ont, cfsn, vbrowser, etc), are certainly NOT included in this proposal at all; those in fact represent plans for improvements, including better modularization, etc.

That said, I will be OK with whatever strategy you think is best/more practical, really.

**Comment by graybeal** [comment]
The issues are imported to GitHub's mmisw/mmiorr repository, and the assignees assigned, as long as the assignee is you or me. 

All the other non-blank assignees have an assignee of mmisw, so you can filter on assignee=mmisw and see those. It will be easy to assign them but I have to add them as collaborators (not sure we want to do that) or create some labels ('assignee-BobArko') -- either way I have to log in as mmisw, I don't have enough permissions as me. 

An email needs to be sent out to collaborators.

**Comment by graybeal** [comment]
Previous repository was forwarded from Google code, which unfortunately (unbelievably) has closed access to the content irreversibly (so far at least). Issue https://code.google.com/p/support/issues/detail?id=33898 filed with google code.

**Comment by carueda** [comment]
Replaced all links to issues in https://marinemetadata.org/orrstatus to point to this Github tracker.
