### ISSUE TITLE
URL for simple list by authority doesn't work for CUAHSI

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#333]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on November 26, 2014 21:35:37_

What steps will reproduce the problem? 1. For comparison, go to http://mmisw.org/ont/ioos 2. Go to http://mmisw.org/ont/cuahsi What is the expected output/behavior? A simple list of CUAHSI vocabularies, like the one for IOOS. (Problem originally identified by Emilio Mayorga, who prefers this presentation of information for some customers to the more complete information available at http://mmisw.org/orr/#ba/cuahsi. ) What do you see instead? A 500 error:
HTTP Status 500 -

type Exception report

message

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.NullPointerException
	org.mmisw.ont.MiscDispatcher$1.compare(MiscDispatcher.java:131)
	org.mmisw.ont.MiscDispatcher$1.compare(MiscDispatcher.java:129)
	java.util.TimSort.countRunAndMakeAscending(TimSort.java:325)
	java.util.TimSort.sort(TimSort.java:189)
	java.util.TimSort.sort(TimSort.java:173)
	java.util.Arrays.sort(Arrays.java:659)
	java.util.Collections.sort(Collections.java:217)
	org.mmisw.ont.MiscDispatcher.listOntologiesForAuthority(MiscDispatcher.java:129)
	org.mmisw.ont.OntServlet._dispatchAuthority(OntServlet.java:348)
	org.mmisw.ont.OntServlet._dispatch(OntServlet.java:236)
	org.mmisw.ont.OntServlet.doGet(OntServlet.java:319)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.40 logs. What version of the product are you using? (You can see the version at the bottom of the ORR page.) ORR Portal 2.1.2 (201410080025) If relevant, please attach the file you were working on (for submission of new ontology, text for import in the vocabulary interface, etc.). If possible and relevant, please provide a screen shot showing the problem. Please provide information about your browser and version (Firefox, Safari, Chrome, IE, etc.), operating system, etc. Google Chrome on Mac Version 38.0.2125.122

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=333_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on November 26, 2014 21:36:55_

If this is easy to fix, it could be kind of valuable to fix, in terms of Emilio using ORR features to communicate with customers.

If it's hard, then it isn't critical.

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 27, 2014 11:03:32_

Seems like a straightforward fix, which I'll try to complete shortly, but deployment may be delayed as I'm not able to VPN the server at the moment.

**Status:** Accepted  
  **Labels:** -mmiorr ont

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 27, 2014 11:38:32_

Fixed in Ont service 2.1.3.
Testing pending once the new version can be deployed. Will add a note when that happens.

**Status:** Fixed

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 02, 2014 08:27:59_

Version 2.1.3 (201412021018) deployed and fix verified. http://mmisw.org/ont/cuahsi now shows a list of about 20 ontologies.

Note: one of the entries in the list is: http://mmisw.org/testing/CUAHSI/TEST_aquabiocompound which seems to have triggered the NPE in the previous version, most likely because it is actually a re-hosted entry that happens to follow the MMI URI structure. Look into this a bit more when time permits.

**Status:** Verified

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 03, 2014 16:50:00_

Here is the issue entered for the observation above: Issue 334 (github would have cross-referenced it automatically ;)

**Comment by graybeal** [comment]
Reopening issue because symptoms are back.  We need to decide whether to fix it or let it go.

It occurs to me the problem may have been caused by my addition of a test CSDMS vocabulary, trying to make it follow our pattern although it is remotely hosted. That would be https://mmisw.org/orr/#http://www.isi.edu/ikcap/geosoft/ontology/csdms, more than likely.
