### ISSUE TITLE
require telephone number from new users

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#335]
_From [jgrayb...@mindspring.com](https://code.google.com/u/102751489721050826906/) on December 28, 2014 19:28:09_

What capability do you want added or improved? 
New registered users of ORR should be required to provide a telephone number 

Where do you want this capability to be accessible? 
Enforced by the registration form 

What sort of input/command mechanism do you want? 
see above 

What is the desired output (content, format, location)? 
Phone number in the user database. 

Other details of your desired capability? What version of the product are you using? Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, Chrome, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=335_

**Comment by carueda** [comment]
In ORR3, this field is required and uses the standard
 [`type="tel"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).
