### ISSUE TITLE
Evaluate risk of SPARQL denial of service query, options for reducing

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#336]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on January 19, 2015 20:41:55_

What capability do you want added or improved? 
I'd like to know if there is risk that the server could be affected by a too-complex SPARQL query. If so, take a look at this approach to minimizing the exposure of the SPARQL servers. http://linkeddatafragments.org (Paul Alexander has vetted this approach with some of his colleagues.) 

Where do you want this capability to be accessible? 
To be determined. 

What sort of input/command mechanism do you want? 

What is the desired output (content, format, location)? Other details of your desired capability? What version of the product are you using? Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=336_

**Comment by carueda** [comment]
Closing as won't fix.

John: feel free to open a new one in the new system if you think this should still be addressed, perhaps with additional information ..
