### ISSUE TITLE
Allow to load a remote file

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#34]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 07, 2008 13:39:45_

Nonong's suggestion: allow not only the loading of a local file, but also a
remote one, for example using an HTTP address.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=34_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 10, 2008 14:07:48_

**Labels:** -Priority-Medium Priority-Low

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 29, 2008 16:59:18_

**Labels:** -org.mmisw.ontmd ontmd

**Comment by carueda** [comment]
In new ORR3:
- https://github.com/mmisw/orr-ont/issues/39
- https://github.com/mmisw/orr-portal/issues/79
