### ISSUE TITLE
dropdown term lists include all #included ont terms, but not all of them resolve

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#340]
As noted in #338, for ingested ontologies with includes, sometimes not every token displayed in our drop-downs is included in the final set of resolvable terms. It turns out (I'm guessing, based on a few tests) that the drop-downs include all the terms from the included ontologies, but we only resolve the terms that are actually in the main ontology that was imported. Since one can't tell the difference by looking at the UI, it creates an apparent inconsistency.

Three options to fix: (1) Don't include included terms in the drop-down lists, that aren't in the directly ingested ontology itself. (2) Label the terms in the drop-down lists that are not included in this ontology. (3) Resolve all the terms, in not just the original ontology but any #includes.

I don't like (3) because it could be a very long list. The same argument suggests (2) is not the preferred option (as drop-down lists could be cluttered with unused terms from include vocabularies). 

Option (1) seems best because it most closely matches the actual ontology file that was loaded.

**Comment by graybeal** [comment]
Copied from Carlos' comment on #345: 

_A general comment: This is likely an incorrect way to operate, but most (if not all) operations in the ORR are basically centered around the URI of the ontology itself, in particular for reporting of terms. That is, it only reports the terms under the namespace defined by the ontology URI. (I'll have to look into the code to confirm this behavior as I'm be forgetting the key details.)_

I think it is a reasonable starting point; knowing about imported terms is also important, but I suggest that's secondary. (In order to include them, we would need to be able to differentiate them, which is a bit of work.)

I *think* the problem I noted above is that some imported terms are included in the list. Not 100% confident, some checking may be in order.

**Comment by carueda** [comment]
Just noting that this entry can be closed (as fixed) due to recent updates, in particular, a fix in a couple of places in the code where `owl:import`'ed ontologies were loaded by mistake. This was fixed in commit 9c3034dd61b12c236ac7f83f19696372a037e2e0 

Besides, that change just "happens" to align with your preferred suggestion `;)`

> (1) Don't include included terms in the drop-down lists, that aren't in the directly ingested ontology itself.
> ...
> Option (1) seems best because it most closely matches the actual ontology file that was loaded.
