### ISSUE TITLE
add information to authority, acronym pop-up help

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#341]
Update the Authority abbreviation pop-up help to include the following sentence: "For locally hosted ontologies, the authority abbreviation is used in the unique identifier string (URI) after the ontology path (`http://mmisw.org/ont/`). "

Update the Acronym abbreviation to include the following sentence: "For ORR's locally hosted ontologies (the default), the acronym is is used in the unique resource identifier string (URI) after the authority abbreviation; it is the final fragment in an unversioned ontology URI, and the next-to-last fragment in an unversioned term URI."

**Comment by carueda** [comment]
Fixed in v3.
