### ISSUE TITLE
streamline installation of ORR system

### ISSUE THREAD

**Issue by carueda** [mmisw/mmiorr#353]
This task is about reviewing current procedure to install the MMI ORR on a new server, and doing changes for simplification. The focus here is on the two main components Ont service and ORR Portal, not on the pre-requisites on the target system (including Java; Apache HTTP server amd Tomcat Servlet Container; MySQL server; AllegroGraph Server).

**Comment by graybeal** [comment]
It potentially overlaps with my tasks on the COR project (https://github.com/ESIPFed/cor/issues for the issues). In particular I am ready 'any day now' to create an AWS server and start installing. How do we want to coordinate that with this task, any particular recommendations?

**Comment by carueda** [comment]
I'd suggest:
* at time of installation, use whatever latest version is available at the upstream repo https://github.com/mmisw/mmiorr/
* this in part because I may be able to make progress on simplifying the needed configuration and installation process. This might likely be a bit incremental depending on how fast I can be. But the idea is that you can avoid duplication on effort for this. Of course, if you have suggestions, please put them in this issue.
* The parts related with prerequisites are not going to change (at least not for now), so, besides VM characteristics that could be similar to those at TAMU, you can follow corresponding notes at https://github.com/mmisw/mmiorr/wiki/install for those.

Sound good?

**Comment by graybeal** [comment]
I think is fine, yes.  Just wanted to be sure we weren't going to collide or duplicate or undercut. I think it should be fine.

**Comment by carueda** [comment]
Related:
- #351 
- #268 
- #283

**Comment by carueda** [comment]
Possible alternative approaches to facilitate installation includes Docker and a PAAS provider like Heroku where you can just basically give them the WARs and they take care of the rest.  I know Amazon AWS is more an IAAS but perhaps they provide something similar?

**Comment by carueda** [comment]
@graybeal : if you are interested in exploring Docker @ AWS (https://www.docker.com/aws), I can try set up a docker container with the whole ORR system in it (centos, mysql, tomcat, even perhaps allegrograph, and the ont and portal apps). Docker is a must-learn technology nowadays so this would be a good chance.

**Comment by graybeal** [comment]
Sorry for the late response, by all means try setting Docker up. Though I'm trying to get through this the fastest way I can, so if that turns into major investigation time I may not pursue it. But the point is, it shouldn't be major investigation time, if an install can be packaged. 

I think setting up an AWS install is another thing worth investigating -- even faster than docker for AWS installers I expect. But it can wait its turn.

**Comment by carueda** [comment]
Fixed in v3.
