### ISSUE TITLE
add metadata attribute for ontology to reference previous version

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#381]
OMV has added an attribute to relate an ontology to its predecessor. I think we should add this attribute and automatically populate it.

**Comment by carueda** [comment]
Any specific pointers for this?

**Comment by graybeal** [comment]
Oops. Took me an hour to find where I really saw it.

OWL 2 has the annotation and property `priorVersion`. See http://www.w3.org/TR/owl2-syntax/ -- salient section is http://www.w3.org/TR/owl2-syntax/#Ontology_Annotations, which says "The owl:priorVersion annotation property specifies the IRI of a prior version of the containing ontology."

It can also indicate whether it is compatible with the previous version (or vice versa, I'm a little confused) through the owl:backwardCompatibleWith and owl:incompatibleWith annotation properties, same section.

Just to document the OMV reference, though it's not relevant to this question: OMV home page is http://omv2.sourceforge.net, it's severely under-maintained. The ontology is at http://sourceforge.net/projects/omv2/files/OMV%20Core%20Ontology/OMV_v2.4.1.owl/download, if you can find your way through SourceForge without downloading junk ware. OWL file is copied here (with .txt extension, take that off to use). 

[OMV_v2.4.1.owl.txt](https://github.com/mmisw/mmiorr/files/46749/OMV_v2.4.1.owl.txt)

**Comment by graybeal** [comment]
Side note: DOOR is another versioning ontology that is pretty comprehensive. But I don't think we need it at the moment. http://watson.kmi.open.ac.uk/DownloadsAndPublications_files/keod09.pdf

**Comment by carueda** [comment]
I know about the OWL version-related properties but from your initial description I thought you were specifically suggesting some property from the OMV vocabulary.  Then "... though it's not relevant to this question: OMV home page is..." got me more confused. 

Anyway, more in general, just wondering whether OMV is actually relevant ... perhaps we can just stick with more standard vocabularies (OWL, DC, DCT..)?

**Comment by carueda** [comment]
Let's simply summarize this entry specifically about using **owl:priorVersion** 

Rationale: 
- this is a very well-established property for this purpose
- investigating alternatives would require some extra effort 

I'm closing this one here, and opening https://github.com/mmisw/orr-portal/issues/91
