### ISSUE TITLE
Insert ontology annotation property for issue tracker location

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#382]
Add an annotation property for any ontology that describes the location of the issue tracking system for that ontology. (Ideally it tracks issues only for that ontology, but if it's part of a larger project, so be it.)

The issue tracker should be a 'resolvable with proper authority' IRI -- that is, it may be an IRI that is only available to the ontology maintainers, though this is discouraged (of course :-).

Suggest calling it hasIssueTrackingLocation (hmm, thought about forcing it to be a URL, but I wasn't sure if 'URL' is still the name for a resolvable IRI).

**Comment by carueda** [comment]
Closing as "won't fix".  If really needed, open issue in new trackers.
