### ISSUE TITLE
don't reversion terms with every revision of ontology

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#39]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on November 11, 2008 13:13:40_

What steps will reproduce the problem? 
1. Create new version of existing ontology.
2. Look at ontology output in HTML. 

What is the expected output? 

What do you see instead? 
We want the terms to maintain their older URIs if they are not changed. Right now all the terms 
get new URIs, corresponding to the new version of the ontology. 

Please use labels and text to provide additional information. 
This has been discussed on semantic-web@w3c.com and internally. While we can't be 
absolutely sure, this is probably (>95&#37;) the right approach.
  To do this, you'll have to parse all the concepts in the ontology, determine which ones have 
changed, and only generate new URIs with new revisions for the changed ones.  All the other 
URIs will stay the same.
  I wanted to give this a milestone "UrgentAfterWorkshop", but couldn't figure out how.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=39_

**Comment by mmisw** [comment]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on November 11, 2008 13:20:28_

Figured out how to add milestone. And updated priority, it's important but not a crisis.

**Labels:** -Priority-Medium Priority-High Milestone-ASAPafterWorkshop

**Comment by mmisw** [comment]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on November 11, 2008 13:31:27_

not a defect, a change of what we wanted

**Labels:** -Type-Defect Type-Enhancement

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 13:10:01_

Examine the ways a term can change.

**Comment by mmisw** [comment]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on February 20, 2009 13:15:24_

This is really important.

**Labels:** -Priority-High Priority-Critical

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on March 16, 2009 22:59:59_

Here is one more consideration:

"Right now all the terms get new URIs, corresponding to the new version of the
ontology." Yes, that's right. Note however that these new URIs are different ONLY
because of the new version. So, in terms of the "unversioned" form, the URIs haven't
actually changed. Since we are currently making our whole system to be
"unversioned"-oriented (meaning that versioned URIs are provided only when explicitly
requested), perhaps this scheme is already sufficient to handle this enhancement
request, at least for the time being (and if so, we could just lower the priority)?

**Status:** Diagnosed  
  **Owner:** carueda  
  **Cc:** grayb...@mbari.org  
  **Labels:** ontmd ont

**Comment by mmisw** [comment]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on March 17, 2009 08:23:47_

I agree, since most users will only see (and care about) unversioned URIs, this is not as critical an upgrade. 
Changed it to High (because otherwise we will accumulate lots of versioned terms that aren't any different from 
the previous version). 

When we make this change, it will be important to get the annotations and/or relationships right, so that the 
relationship of a new version of a term to the one that preceded it is clear.

**Labels:** -Priority-Critical Priority-High

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on August 10, 2009 18:58:25_

**Cc:** -grayb...@mbari.org  
  **Labels:** -Milestone-ASAPafterWorkshop

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 05, 2010 17:34:49_

(bulk edit): REmoved Beta1 label per discussion today (John and Carlos)

**Labels:** -Milestone-Beta1

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 10:33:24_

I am not so sure that this is important at this stage. There are some people who feel strongly reversioning all the terms is inappropriate; I think it's likely not a critical issue. It would be nice if it were trivial to detect when a term last changed by using its timestamp; but it also is nice to see whether a term is part of a particular vocabulary by using its timestamp. By making this change, the second use case is disabled, while the first one is enabled. In either case, it would be nice if the disabled use case is satisfied through some other feature of the tool.

Plus, I don't buy the argument that a term's meaning can stay unchanged when the vocabulary is versioned; I think the context provided by the vocabulary as a whole affects the meaning of the term considerably.

I am therefore setting the Priority to Low for this for now. It can always be raised if a need arises.

**Labels:** -Priority-High Priority-Low

**Comment by carueda** [comment]
Closing as "won't fix".  If something like this is really needed, submit a "fresh" entry in relevant ORR3 tracker.
