### ISSUE TITLE
new space for documentation

### ISSUE THREAD

**Issue by carueda** [mmisw/mmiorr#393]
As suggested during the XDOMES meeting, Dec 2015.

**Comment by carueda** [comment]
Let's go ahead with Sphinx.

One other ref: http://docs.readthedocs.org/en/latest/getting_started.html

On my local machine as well as on `mmisw`:

```shell
$ sudo easy_install pip
$ pip install sphinx sphinx-autobuild
$ sudo pip install sphinx sphinx-autobuild
```

Then pushed this to the new repo https://github.com/mmisw/mmiorr-docs

**Comment by carueda** [comment]
Well, having to learn a new syntax (rst) is not a very productive way to spend my time now, so I just switched to use http://www.mkdocs.org/, which uses old well-known markdown and is actually very easy to set up and use.  Also, it is the system used by http://docs.opensensorhub.org/ so we can leverage their expertise if the need arises.

**Comment by fgayanilo** [comment]
yes, that will be a good idea; I have started to learn mkdocs myself.

**Comment by carueda** [comment]
Good!

**Comment by carueda** [comment]
Just deployed the skeleton to http://mmisw.org/doc/ -- Of course, not to be publicized just yet

**Comment by carueda** [comment]
- Repo created: https://github.com/mmisw/mmiorr-docs
- Tracking to continue at https://github.com/mmisw/mmiorr-docs/issues
