### ISSUE TITLE
support status keyword and message on every page

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr#399]
It will be important that users (both end users, and developers) be able to distinguish a production system from an in-development or demo system. This is to cover the use cases when we're showing people the system, but it may not be ready for them to use, or it may not have finalized its URL path, or maybe it's just in maintenance mode temporarily.  (There used to be a small indicator showing 'beta' near the title.)

The proposed solution is a *status attribute*, with values Demo/Sandbox, Prototype, Alpha, Beta, and Production; plus a *status notes* field, which is free text HTML entered by the admin. The status attribute shows up in an appropriate place at the top of each page; and the free text notes field is displayed (when non-empty) in a box at the top of every page. The box should auto-size to include the content in the status notes field.

**Comment by carueda** [comment]
There's a mechanism to insert HTML fragments, one at the top of every page and one at the bottom of every page.  

Assuming the `workspace` property in `mmiorr.conf` is:
```
workspace = /opt/MMI-ORR/workspace
```
then the corresponding files with these fragments are:

- `/opt/MMI-ORR/workspace/_btop.html` for the header
- `/opt/MMI-ORR/workspace/_bbot.html` for the footer

To facilitate conditional inclusion of the fragment without having to remove the file itself, a line in the file with the special comment:
```
# ignore: yes
```
can be used to indicate whether to ignore (as shown) or include the file.

Perhaps this mechanism can provide the requested enhancement here?

**Comment by graybeal** [comment]
ok, this is more than adequate. I like the idea of having an attribute but I don't really have a use case for it. (Well, only a minor use case -- the ability to tell what stage of maturity a deployment is in, without having to have a big header at the top of the page.)  I think we can keep that in the back of our minds for some future opportunity.
