### ISSUE TITLE
correctly relate new term versions to old

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#48]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on November 12, 2008 22:20:14_

What capability do you want added or improved? 
When a new version of a term is generated, some ontology magic should relate it to the previous 
term, and the previous term should be related forward. 

Where do you want this capability to be accessible? 
In inferencing engines, and in metadata for the term. 

What sort of input/command mechanism do you want? 
Should happen automatically, no user input required.

 What is the desired output (content, format, location)? 
Ontology relationships that carry the relationships; not sure where they should live. 

Other details of your desired capability? 
You could create all these relationships (at least the forward-mapping ones) in a second 
ontology, that manages all the versioning. It will essentially contain a version history for all term 
changes, expressed as newOne IsNewVersionOf oldOne, or whatever the appropriate relationship 
is; and vice-versa. (Well, vice-versa is the inverse, so it is a free inference.)  

Hmm, as I think about it more, probably better if that statement can be made in the original 
ontology.

I have no idea what the right relationship is, though.  Don't think SKOS has one. What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of 
vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, 
etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=48_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:05:27_

**Owner:** grayb...@marinemetadata.org

**Comment by graybeal** [comment]
This is the same request (roughly) as #49, and for the same reasons explained in #49, is probably not a particularly helpful improvement. (What we might create at some point is the OMV metadata for the ontology, pointing back to its previous version; see #381.)

Marking this as wontfix.
