### ISSUE TITLE
mapping from versioned to unversioned terms and vice-versa

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#49]
_From [grayb...@mbari.org](https://code.google.com/u/109634240660495836000/) on November 12, 2008 22:27:56_

What capability do you want added or improved? 
- (1) When each term is put in an ontology, it should include a mapping that explicitly points to 
the unversioned term as well; and 
- (2) when an unversioned output is delivered, the unversioned terms should have a mapping to the versioned terms. 

Where do you want this capability to be accessible? 
In ontology relationships: 
- (1) in the original ontology 
- (2) in the unversioned output 

What sort of input/command mechanism do you want? 
Should happen automatically. 

What is the desired output (content, format, location)? 
In addition to having the relations in the ontologies, we should modify the HTML to show them. 

Other details of your desired capability? 
Probably need to build the relations concepts (inverse):
```
    isUnversioned
    isVersioned 
```
What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of 
vocabulary (voc2rdf), operating system, browser/version (Firefox, Safari, IE, etc.), screenshot, 
etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=49_

**Comment by mmisw** [comment]
_From [jbgrayb...@mindspring.com](https://code.google.com/u/106719590578390745654/) on August 22, 2014 11:05:11_

**Owner:** grayb...@marinemetadata.org

**Comment by carueda** [comment]
I think this needs a very careful review and justification. 
My inclination is to close as "won't fix" and let concrete use cases to drive the possible revival of a feature like this.

**Comment by graybeal** [comment]
Well, there were a lot of concrete use cases in my mind when I suggested it, but I'm not sure I have a very good understanding of the real consequences of making the requested change.

* Use case: Show me the various versions of this term (and highlight those that reflect actual changes in the term's attributes).
* Use case: For a given versioned term, show me its unversioned counterpart.
* Use case: Show me which version of an unversioned term was current as of a given timestamp.

Now that you show (at least in the UI -- is there an API for it?) the versions of an ontology, I think there are probably better ways to solve all those use cases then to create the relations proposed here and use SPARQL queries. So marking it as dontfix seems like the right thing.
