### ISSUE TITLE
search mappings by given confidence level

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#68]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 19, 2008 08:22:36_

TBD What capability do you want added or improved? Where do you want this capability to be accessible? What sort of input/command mechanism do you want? What is the desired output (content, format, location)? Other details of your desired capability? What version of the product are you using? Please provide any additional information below (particular ontology/ies,
text contents of vocabulary (voc2rdf), operating system, browser/version
(Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=68_

**Comment by carueda** [comment]
Won't fix.
