### ISSUE TITLE
provide group access to update/edit vocabularies

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#72]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 19, 2008 08:42:49_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information. might be through projects
keep it under control of creator (e.g., GoogleDocs)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=72_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 19, 2008 08:43:25_

**Labels:** -Priority-Medium Priority-High

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 13:23:01_

**Labels:** -Priority-High Priority-Medium

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 25, 2009 11:24:01_

**Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-High

**Comment by mmisw** [comment]
_From [ber...@gmail.com](https://code.google.com/u/105051227815968870037/) on December 11, 2009 08:44:06_

Create group information in an ontology

Group has:
- members ( can me a member)
- manager ( adds and removes members and ontologies )
- list of ontologies

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 22, 2009 00:05:08_

priority critical per OOI Semantic prototype requirement.

**Labels:** -Priority-High Priority-Critical ooici Usability

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on January 05, 2010 12:53:37_

Issues to be resolved for Beta 1 release

**Labels:** Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 05, 2010 17:34:49_

(bulk edit): REmoved Beta1 label per discussion today (John and Carlos)

**Labels:** -Milestone-Beta1

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 05, 2010 17:42:00_

**Labels:** -Priority-Critical Priority-High

**Comment by carueda** [comment]
Possible in v3, where a submission can be owned by a given "organization", whose members will have these privileges.
