### ISSUE TITLE
resolve ontology version at a given time

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#83]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 07:50:54_

What capability do you want added or improved? A service that responds with the version of a certain ontology at a given time. Where do you want this capability to be accessible? The "ont" service might be a good place, something like: http://mmisw.org/ont/auth/vocab/?at=20081120T000000 What is the desired output (content, format, location)? The request could be dispatched by a _redirect_ to the versioned ontology
corresponding to the requested date/time.

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=83_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 07:53:40_

**Labels:** -Priority-Medium Priority-High

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 13:24:14_

**Labels:** -Priority-High Priority-Low

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 01, 2009 10:53:51_

(just tagging with "ont" --instead of "org.mmisw.ont" which is deprecated)

**Labels:** -org.mmisw.ont ont

**Comment by carueda** [comment]
simply won't fix.
