### ISSUE TITLE
Subscribe to changes

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#85]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 08:32:33_

What capability do you want added or improved? 
Some mechanism that notifies users when an ontology changes (a new version
is created) 

Where do you want this capability to be accessible? 
TBD

What sort of input/command mechanism do you want? 
TBD 

What is the desired output (content, format, location)? 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies,
text contents of vocabulary (voc2rdf), operating system, browser/version
(Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=85_

**Comment by carueda** [comment]
https://github.com/mmisw/orr-portal/issues/86
