### ISSUE TITLE
Draft entries for vocabularies

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#86]
_From [steve...@gmail.com](https://code.google.com/u/106701482134906275152/) on November 20, 2008 12:45:12_

What capability do you want added or improved?  
It would be nice if there was a draft capability for registering vocabularies.  That way, one could store partially finished work, access it and complete it at a later time, and then register it.

Where do you want this capability to be accessible?  
This should be accessible from Voc2RDF.

What sort of input/command mechanism do you want?  
A button to store a draft of the vocabulary, and a way to call it back up later. 

What is the desired output (content, format, location)? 

Other details of your desired capability? 

What version of the product are you using? 

Please provide any additional information below (particular ontology/ies, text contents of vocabulary (voc2rdf), operating system, browser/version 
(Firefox, Safari, IE, etc.), screenshot, etc.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=86_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on November 20, 2008 13:57:36_

**Owner:** carueda

**Comment by carueda** [comment]
Overall 'status' handling much improved in v3.
