### ISSUE TITLE
URLs for Summary Ontologies

### ISSUE THREAD

**Issue by mmisw** [mmisw/mmiorr#91]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on December 29, 2008 14:44:31_

What capability do you want added or improved? 
From: http://marinemetadata.org/apguides/ontprovidersguide/ontguideconstructinguris 

>... the following summary ontologies can be useful: 
>
> (1) an ontology defining the top concepts contained in the resources that are made available, and 
> (2) an overarching ontology, which imports all the latest versions of the ontologies available in that host. 

Where do you want this capability to be accessible? 
Through the Ontology URI Resolver. 

Other details of your desired capability? 
(This issue entry is mainly a placeholder while the details of the various related functionalities are specified in more detail.)

_Original issue: http://code.google.com/p/mmisw/issues/detail?id=91_

**Comment by mmisw** [comment]
_From [caru...@gmail.com](https://code.google.com/u/113886747689301365533/) on April 01, 2009 10:53:28_

(just tagging with "ont" --instead of "org.mmisw.ont" which is deprecated)

**Labels:** -org.mmisw.ont ont

**Comment by carueda** [comment]
As said in the referenced MMI page, the "URLs for Summary Ontologies" section represents
>  ongoing discussion. It has not been extensively reviewed and has not been implemented in MMI services.

My inclination is to *not* provide any automated support for such summary ontologies.

**Comment by graybeal** [comment]
Having been paying modest attention to the last 5 years of ontology development practices, I do not see the first of these suggestions as implementable, and I don't see the second as useful. Specific uber-ontologies should be created for specific purposes from specific sub-collections, all of which is a manual process and outside the scope of ORR.

I propose this be marked wontfix, please do so if you agree.

**Comment by carueda** [comment]
> Specific uber-ontologies should be created for specific purposes from specific sub-collections, all of which is a manual process and outside the scope of ORR.

Agree.
